-- migrate:up
CREATE TABLE test_items (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug text NOT NULL UNIQUE,
    name text NOT NULL,
    description text,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_test_items_updated_at
BEFORE UPDATE ON test_items
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

INSERT INTO test_items (id, slug, name, description, is_active)
VALUES
    (1, 'alpha', 'Alpha item', 'Seed row for the first test item.', true),
    (2, 'bravo', 'Bravo item', 'Seed row for the second test item.', true),
    (3, 'charlie', 'Charlie item', 'Inactive seed row for filtering examples later.', false)
ON CONFLICT (slug) DO UPDATE
SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active,
    updated_at = now();

SELECT setval(pg_get_serial_sequence('test_items', 'id'), (SELECT max(id) FROM test_items));

-- migrate:down
DROP TABLE IF EXISTS test_items;
